--- #YAML:1.0
name: Array-Compare
version: 1.11
author:
  - Dave Cross <dave@mag-sol.com>
abstract: Perl extension for comparing arrays.
license: perl
requires:
  perl: 5.6.0
provides:
  Array::Compare:
    file: lib/Array/Compare.pm
    version: 1.11
generated_by: Module::Build version 0.25
