---
name: Array-Compare
version: 1.13
author:
  - Dave Cross <dave@mag-sol.com>
abstract: Perl extension for comparing arrays.
license: perl
requires:
  perl: 5.6.0
provides:
  Array::Compare:
    file: lib/Array/Compare.pm
    version: 1.13
generated_by: Module::Build version 0.261
